### ISSUE TITLE
Serialisation bug

### ISSUE THREAD

**Issue by MFlisar** [dkunzler/esperandro#51]
I have a field like following in my preferences to show some info cards to my users and to know which one they have already seen and dismissed:

    List<String> hiddenInfos();
    boolean hiddenInfos(List<String> hiddenInfos);
    void hiddenInfos$Add(String toAdd);
    void hiddenInfos$Remove(String toRemove);

After my last relase I suddenly got a lot of crash reports like following:

	[SerializationUtil:43 deserialize]: java.io.InvalidClassException: com.my.app.prefs.PreferenceManager$$Impl$HiddenInfos; Incompatible class (SUID): com.my.app.prefs.PreferenceManager$$Impl$HiddenInfos: static final long serialVersionUID =8736114807095266538L; but expected com.my.app.prefs.PreferenceManager$$Impl$HiddenInfos: static final long serialVersionUID =3661852850784779536L;
		at java.io.ObjectInputStream.verifyAndInit(ObjectInputStream.java:2343)
		at java.io.ObjectInputStream.readNewClassDesc(ObjectInputStream.java:1643)
		at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:657)
		at java.io.ObjectInputStream.readNewObject(ObjectInputStream.java:1784)
		at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:761)
		at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1985)
		at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1942)
		at com.swissarmy.utils.SerializationUtil.deserialize(SerializationUtil.java:40)
		at com.my.app.MainApp$1.deserialize(MainApp.java:76)
		at com.my.app.prefs.PreferenceManager$$Impl.hiddenInfos(PreferenceManager$$Impl.java:1182)
		at com.my.app.managers.UpdateManager.onAppStart(UpdateManager.java:208)
		at com.my.app.MainApp.onAfterOnCreate(MainApp.java:151)
		...
		
I would expect that the `serialVersionUID` is constant... Maybe it makes sense to define a custom one via annotations? To avoid that the `serialVersionUID` is constant as this is essential for deserialisation...

**Comment by dkunzler** [comment]
Hmm, interesting. I can't imagine why it changed. I didn't change the implementation of the container classes. Did you change something in the range of:
* package name of the preferences
* name of parameter `hiddenInfos`
* type of `hiddenInfos`

Normally the serialVersionUid should not change.
I could generate a constant one, but the question is if this helps or if there arise other problems. ObjectStream serialization is not the stablest thing, especiaally across Java (=Android) versions and different versions of the app.

**Comment by MFlisar** [comment]
I was aware of this possible problem, so I did not change the preference's class package name nor the field's name nor it's type.

What I do though is using two computers to build my app, not 100% sure if this may lead to different `serialVersionUID`, do you know this?

**Comment by dkunzler** [comment]
I am now generating a serialVersionUID for the generated container classes. So please be aware when updating that this will definately trigger now this Exception.

2.7.0 will be available as soon as maven central is synced.

**Comment by MFlisar** [comment]
That's fine for me, I only use one `ArrayList` where I save already seens user infos/tipps so it's no big deal here.

Thanks for all the effort.
