### ISSUE TITLE
Default for serialize values does not work

### ISSUE THREAD

**Issue by jbirtel** [dkunzler/esperandro#74]
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 2 path $
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
        at com.google.gson.Gson.fromJson(Gson.java:927)
        at com.google.gson.Gson.fromJson(Gson.java:892)
        at com.google.gson.Gson.fromJson(Gson.java:841)
        at com.google.gson.Gson.fromJson(Gson.java:813)
        at de.devland.esperandro.serialization.GsonSerializer.deserialize(GsonSerializer.java:44)
        at de.srt.vault.prefs.SimpleStorage$$Impl.unprocessedEvents(SimpleStorage$$Impl.java:61)
        at de.srt.vault.util.InitializationUtil.processContactEvents(InitializationUtil.java:95)
        at de.backessrt.wb.ui.main.MainActivity.servicesReady(MainActivity.java:186)
        at de.backessrt.wb.ui.main.MainActivity.onActivityResult(MainActivity.java:442)
        at android.app.Activity.dispatchActivityResult(Activity.java:8318)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5089)

**Comment by dkunzler** [comment]
should be fixed in 4.0.1

It will not be backported to the 3.x line. So @jbirtel please add "upgrade esperandro to 4.0.x" to the Checklist "refactorings" in our Vault project.
